# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6abe84e6de64d20d152e302b93e4859bc1b80201c075444685f76a7093fa5074cf4a669d64599269b85f319ef8eddb3cd6fa47c1773a598ad2b01327721c791

test:
  secret_key_base: 3e4c67de6fcfb99f8c034a8a5f80f90a4ca5ee97f877b2f06c281e1ea9a14a42a3acc08c7edb17f82cb63aa157a4ef3724187a61e2546a805ed92b73311dd68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
